"""
services/tone_data.py
All dictionaries, rules, and reference data for the rule-based tone engine.
No API key required.
"""

# ──────────────────────────────────────────────────────────────────────────────
# CONTRACTIONS — expand (casual→formal) or contract (formal→casual)
# ──────────────────────────────────────────────────────────────────────────────

CONTRACTIONS_EXPAND = {
    "can't": "cannot",
    "won't": "will not",
    "don't": "do not",
    "doesn't": "does not",
    "didn't": "did not",
    "isn't": "is not",
    "aren't": "are not",
    "wasn't": "was not",
    "weren't": "were not",
    "hasn't": "has not",
    "haven't": "have not",
    "hadn't": "had not",
    "wouldn't": "would not",
    "shouldn't": "should not",
    "couldn't": "could not",
    "i'm": "I am",
    "i've": "I have",
    "i'll": "I will",
    "i'd": "I would",
    "we're": "we are",
    "we've": "we have",
    "we'll": "we will",
    "we'd": "we would",
    "you're": "you are",
    "you've": "you have",
    "you'll": "you will",
    "you'd": "you would",
    "they're": "they are",
    "they've": "they have",
    "they'll": "they will",
    "they'd": "they would",
    "it's": "it is",
    "it'll": "it will",
    "it'd": "it would",
    "there's": "there is",
    "there'll": "there will",
    "here's": "here is",
    "that's": "that is",
    "that'll": "that will",
    "who's": "who is",
    "who'll": "who will",
    "what's": "what is",
    "let's": "let us",
    "gonna": "going to",
    "wanna": "want to",
    "gotta": "got to",
    "kinda": "kind of",
    "sorta": "sort of",
    "dunno": "do not know",
    "ya": "you",
    "yep": "yes",
    "nope": "no",
    "ain't": "is not",
    "she's": "she is",
    "he's": "he is",
    "she'll": "she will",
    "he'll": "he will",
    "she'd": "she would",
    "he'd": "he would",
    "shouldn't've": "should not have",
    "couldn't've": "could not have",
    "wouldn't've": "would not have",
    "needn't": "need not",
    "mustn't": "must not",
    "mightn't": "might not",
    "shan't": "shall not",
}

CONTRACTIONS_CONTRACT = {v: k for k, v in CONTRACTIONS_EXPAND.items()
                          if not any(c in k for c in ["gonna","wanna","gotta","kinda","sorta","dunno","ya","yep","nope"])}

# ──────────────────────────────────────────────────────────────────────────────
# VOCABULARY — formal ↔ informal word maps
# ──────────────────────────────────────────────────────────────────────────────

INFORMAL_TO_FORMAL = {
    "use": "utilize",
    "start": "commence",
    "end": "conclude",
    "help": "assist",
    "show": "demonstrate",
    "find": "identify",
    "need": "require",
    "get": "obtain",
    "make": "create",
    "look at": "examine",
    "talk about": "discuss",
    "find out": "ascertain",
    "set up": "establish",
    "put together": "compile",
    "come up with": "devise",
    "go over": "review",
    "work on": "address",
    "deal with": "manage",
    "look into": "investigate",
    "check out": "evaluate",
    "lots of": "numerous",
    "a lot of": "a significant number of",
    "big": "substantial",
    "small": "minimal",
    "good": "beneficial",
    "bad": "detrimental",
    "hard": "challenging",
    "easy": "straightforward",
    "fast": "expeditious",
    "slow": "gradual",
    "a lot of": "a considerable number of",
    "lots of": "numerous",
    "kind of": "relatively",
    "sort of": "somewhat",
    "more or less": "approximately",
    "in the end": "ultimately",
    "right now": "at present",
    "right away": "immediately",
    "all the time": "consistently",
    "look at": "examine",
    "talk about": "discuss",
    "find out": "ascertain",
    "set up": "establish",
    "put together": "compile",
    "come up with": "devise",
    "go over": "review",
    "work on": "address",
    "deal with": "manage",
    "look into": "investigate",
    "check out": "evaluate",
    "a lot": "considerably",
    "different": "distinct",
    "same": "identical",
    "important": "paramount",
    "problem": "challenge",
    "answer": "solution",
    "think": "believe",
    "want": "desire",
    "try": "attempt",
    "tell": "inform",
    "ask": "inquire",
    "buy": "purchase",
    "build": "construct",
    "change": "modify",
    "give": "provide",
    "keep": "maintain",
    "stop": "cease",
    "fix": "rectify",
    "many": "numerous",
    "really": "significantly",
    "very": "considerably",
    "just": "simply",
    "only": "exclusively",
    "enough": "sufficient",
}

FORMAL_TO_INFORMAL = {v: k for k, v in INFORMAL_TO_FORMAL.items()}

# Additional casual vocabulary
FORMAL_TO_CASUAL_EXTRA = {
    "utilize": "use",
    "commence": "start",
    "conclude": "finish",
    "assist": "help",
    "demonstrate": "show",
    "identify": "find",
    "require": "need",
    "obtain": "get",
    "ascertain": "figure out",
    "establish": "set up",
    "investigate": "look into",
    "evaluate": "check out",
    "numerous": "lots of",
    "substantial": "big",
    "beneficial": "good",
    "detrimental": "bad",
    "challenging": "tough",
    "straightforward": "easy",
    "approximately": "about",
    "therefore": "so",
    "however": "but",
    "furthermore": "also",
    "paramount": "super important",
    "distinct": "different",
    "identical": "the same",
    "believe": "think",
    "desire": "want",
    "attempt": "try",
    "inform": "tell",
    "inquire": "ask",
    "purchase": "buy",
    "construct": "build",
    "modify": "change",
    "provide": "give",
    "maintain": "keep",
    "cease": "stop",
    "rectify": "fix",
    "critical": "key",
    "primary": "main",
    "ultimately": "in the end",
    "immediately": "right away",
    "currently": "right now",
    "considerably": "a lot",
    "significantly": "really",
    "exclusively": "only",
    "sufficient": "enough",
    "prior to": "before",
    "subsequent to": "after",
    "due to the fact that": "because",
}

# Child-friendly word replacements
CHILD_FRIENDLY = {
    "utilize": "use",
    "commence": "start",
    "conclude": "end",
    "demonstrate": "show",
    "identify": "find",
    "require": "need",
    "substantial": "big",
    "challenging": "hard",
    "straightforward": "easy",
    "approximately": "about",
    "therefore": "so",
    "however": "but",
    "furthermore": "and also",
    "numerous": "many",
    "beneficial": "good",
    "detrimental": "bad",
    "obtain": "get",
    "construct": "build",
    "maintain": "keep",
    "immediately": "right away",
    "currently": "right now",
    "investigate": "look into",
    "significantly": "a lot",
    "ultimately": "in the end",
    "implement": "use",
    "function": "work",
    "generate": "make",
    "analyze": "look at",
    "evaluate": "check",
    "strategy": "plan",
    "facilitate": "help",
    "component": "part",
    "objective": "goal",
    "methodology": "way of doing things",
    "fundamental": "basic",
    "perspective": "view",
    "complex": "complicated",
    "enhance": "improve",
    "impact": "effect",
    "leverage": "use",
    "utilize": "use",
    "optimize": "make better",
    "sufficient": "enough",
    "adequate": "enough",
    "prioritize": "focus on",
    "mitigate": "reduce",
    "accomplish": "do",
}

# Academic word upgrades
ACADEMIC_VOCAB = {
    "use": "employ",
    "show": "illustrate",
    "find": "identify",
    "help": "facilitate",
    "change": "transform",
    "make": "generate",
    "look at": "examine",
    "talk about": "address",
    "think": "posit",
    "big": "significant",
    "important": "pivotal",
    "problem": "phenomenon",
    "try": "endeavor",
    "need": "necessitate",
    "result": "outcome",
    "reason": "rationale",
    "often": "frequently",
    "always": "invariably",
    "many": "numerous",
    "most": "the majority of",
    "good": "efficacious",
    "bad": "deleterious",
    "new": "novel",
    "old": "established",
    "different": "disparate",
    "same": "analogous",
    "clear": "unambiguous",
    "main": "primary",
    "key": "critical",
    "show": "illustrate",
    "find": "identify",
    "help": "facilitate",
    "change": "transform",
    "make": "generate",
    "think": "posit",
    "look at": "examine",
    "talk about": "address",
    "answer": "framework",
}

# Persuasive language additions
PERSUASIVE_STARTERS = [
    "Consider this:",
    "The evidence is clear:",
    "Research demonstrates that",
    "Notably,",
    "It is worth emphasizing that",
    "The data clearly shows that",
    "Undeniably,",
]

PERSUASIVE_CONNECTORS = {
    "also": "moreover",
    "but": "despite this,",
    "however": "yet,",
    "so": "as a result,",
    "because": "given that",
    "and": "furthermore,",
    "but also": "and critically,",
}

# Friendly language additions
FRIENDLY_OPENERS = [
    "Great news —",
    "Here's the thing:",
    "You'll be glad to know that",
    "Let's talk about",
    "Here's something interesting:",
]

FRIENDLY_WARMTH_WORDS = {
    "important": "wonderful",
    "very": "really",
    "good": "fantastic",
    "bad": "tricky",
    "difficult": "a bit challenging",
    "complex": "interesting",
    "simple": "easy and fun",
}

# Executive summary transitions
EXEC_TRANSITIONS = [
    "Key takeaway:",
    "Bottom line:",
    "Action item:",
    "Summary:",
    "Recommendation:",
    "Impact:",
]

# ──────────────────────────────────────────────────────────────────────────────
# SENTENCE STARTERS by tone
# ──────────────────────────────────────────────────────────────────────────────

TONE_SENTENCE_STARTERS = {
    "Formal": [
        "It is worth noting that ",
        "One must acknowledge that ",
        "It should be noted that ",
        "In accordance with the aforementioned, ",
        "It is evident that ",
    ],
    "Casual": [
        "Basically, ",
        "So, ",
        "Look, ",
        "Here's the thing — ",
        "You know what? ",
    ],
    "Friendly": [
        "The great news is that ",
        "Here's something you'll like — ",
        "Let's look at ",
        "You'll find that ",
        "Don't worry, ",
    ],
    "Professional": [
        "Please note that ",
        "It is recommended that ",
        "This indicates that ",
        "The analysis shows that ",
        "Accordingly, ",
    ],
    "Executive Summary": [
        "Key point: ",
        "Action required: ",
        "Summary: ",
        "Bottom line: ",
        "Decision: ",
    ],
    "Persuasive": [
        "The evidence clearly shows that ",
        "It is undeniable that ",
        "Research confirms that ",
        "Consider this — ",
        "Importantly, ",
    ],
    "Child-Friendly": [
        "Did you know that ",
        "Here's something cool — ",
        "Let's think about ",
        "Guess what? ",
        "Here's how it works: ",
    ],
    "Academic": [
        "It can be observed that ",
        "The evidence suggests that ",
        "This analysis demonstrates that ",
        "Research indicates that ",
        "It is posited that ",
    ],
}

# ──────────────────────────────────────────────────────────────────────────────
# AUDIENCE-SPECIFIC settings
# ──────────────────────────────────────────────────────────────────────────────

AUDIENCE_CONFIG = {
    "General Audience": {
        "vocab_level": "neutral",
        "sentence_length_limit": 25,  # max words per sentence
        "use_analogies": False,
        "use_technical_terms": False,
        "jargon_replacement": {},
    },
    "Children": {
        "vocab_level": "simple",
        "sentence_length_limit": 12,
        "use_analogies": True,
        "use_technical_terms": False,
        "jargon_replacement": CHILD_FRIENDLY,
    },
    "Students": {
        "vocab_level": "moderate",
        "sentence_length_limit": 20,
        "use_analogies": False,
        "use_technical_terms": False,
        "jargon_replacement": {},
    },
    "College Students": {
        "vocab_level": "moderate_high",
        "sentence_length_limit": 28,
        "use_analogies": False,
        "use_technical_terms": True,
        "jargon_replacement": {},
    },
    "Professionals": {
        "vocab_level": "high",
        "sentence_length_limit": 30,
        "use_analogies": False,
        "use_technical_terms": True,
        "jargon_replacement": {},
    },
    "Executives": {
        "vocab_level": "high",
        "sentence_length_limit": 20,
        "use_analogies": False,
        "use_technical_terms": False,
        "jargon_replacement": {},
    },
    "Technical Experts": {
        "vocab_level": "expert",
        "sentence_length_limit": 35,
        "use_analogies": False,
        "use_technical_terms": True,
        "jargon_replacement": {},
    },
    "Non-Technical Users": {
        "vocab_level": "simple",
        "sentence_length_limit": 18,
        "use_analogies": True,
        "use_technical_terms": False,
        "jargon_replacement": CHILD_FRIENDLY,
    },
}

# ──────────────────────────────────────────────────────────────────────────────
# TONE CONFIG
# ──────────────────────────────────────────────────────────────────────────────

TONE_CONFIG = {
    "Formal": {
        "expand_contractions": True,
        "contract_contractions": False,
        "vocab_map": INFORMAL_TO_FORMAL,
        "formality_target": 4,
    },
    "Casual": {
        "expand_contractions": False,
        "contract_contractions": True,
        "vocab_map": FORMAL_TO_CASUAL_EXTRA,
        "formality_target": 2,
    },
    "Friendly": {
        "expand_contractions": False,
        "contract_contractions": True,
        "vocab_map": FRIENDLY_WARMTH_WORDS,
        "formality_target": 2,
    },
    "Professional": {
        "expand_contractions": True,
        "contract_contractions": False,
        "vocab_map": INFORMAL_TO_FORMAL,
        "formality_target": 3,
    },
    "Executive Summary": {
        "expand_contractions": True,
        "contract_contractions": False,
        "vocab_map": INFORMAL_TO_FORMAL,
        "formality_target": 4,
    },
    "Persuasive": {
        "expand_contractions": True,
        "contract_contractions": False,
        "vocab_map": INFORMAL_TO_FORMAL,
        "formality_target": 3,
    },
    "Child-Friendly": {
        "expand_contractions": False,
        "contract_contractions": True,
        "vocab_map": CHILD_FRIENDLY,
        "formality_target": 1,
    },
    "Academic": {
        "expand_contractions": True,
        "contract_contractions": False,
        "vocab_map": ACADEMIC_VOCAB,
        "formality_target": 5,
    },
}
